/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AgentsDotmdRouteImport } from './routes/agents[.]md'
import { Route as ApiRouteImport } from './routes/api'
import { Route as BuildWithUsRouteImport } from './routes/build-with-us'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DialogusRouteImport } from './routes/dialogus'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DoutorFiscalRouteImport } from './routes/doutor-fiscal'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as FcrRouteImport } from './routes/fcr'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as QueravagaRouteImport } from './routes/queravaga'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SaoPauloRouteImport } from './routes/sao-paulo'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitecreatorRouteImport } from './routes/sitecreator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ApiOpenapiDotyamlRouteImport } from './routes/api.openapi[.]yaml'
import { Route as ApiV1RouteImport } from './routes/api.v1'
import { Route as ApiVersioningRouteImport } from './routes/api.versioning'
import { Route as CareersIndexRouteImport } from './routes/careers/index'
import { Route as CareersOpenRolesRouteImport } from './routes/careers/open-roles'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as LegalAcceptableUsePolicyRouteImport } from './routes/legal/acceptable-use-policy'
import { Route as LegalBrandGuidelinesRouteImport } from './routes/legal/brand-guidelines'
import { Route as LegalCookiePolicyRouteImport } from './routes/legal/cookie-policy'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal/terms-of-service'
import { Route as LegalTermsOfServiceEnterpriseRouteImport } from './routes/legal/terms-of-service-enterprise'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions/$slug'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkSlugRouteImport } from './routes/work/$slug'
import { Route as ApiV1SplatRouteImport } from './routes/api.v1.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDotmdRoute = AgentsDotmdRouteImport.update({
  id: '/agents.md',
  path: '/agents.md',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildWithUsRoute = BuildWithUsRouteImport.update({
  id: '/build-with-us',
  path: '/build-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogusRoute = DialogusRouteImport.update({
  id: '/dialogus',
  path: '/dialogus',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DoutorFiscalRoute = DoutorFiscalRouteImport.update({
  id: '/doutor-fiscal',
  path: '/doutor-fiscal',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const FcrRoute = FcrRouteImport.update({
  id: '/fcr',
  path: '/fcr',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const QueravagaRoute = QueravagaRouteImport.update({
  id: '/queravaga',
  path: '/queravaga',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SaoPauloRoute = SaoPauloRouteImport.update({
  id: '/sao-paulo',
  path: '/sao-paulo',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitecreatorRoute = SitecreatorRouteImport.update({
  id: '/sitecreator',
  path: '/sitecreator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotyamlRoute = ApiOpenapiDotyamlRouteImport.update({
  id: '/openapi.yaml',
  path: '/openapi.yaml',
  getParentRoute: () => ApiRoute,
} as any)
const ApiV1Route = ApiV1RouteImport.update({
  id: '/v1',
  path: '/v1',
  getParentRoute: () => ApiRoute,
} as any)
const ApiVersioningRoute = ApiVersioningRouteImport.update({
  id: '/versioning',
  path: '/versioning',
  getParentRoute: () => ApiRoute,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersOpenRolesRoute = CareersOpenRolesRouteImport.update({
  id: '/careers/open-roles',
  path: '/careers/open-roles',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAcceptableUsePolicyRoute =
  LegalAcceptableUsePolicyRouteImport.update({
    id: '/legal/acceptable-use-policy',
    path: '/legal/acceptable-use-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalBrandGuidelinesRoute = LegalBrandGuidelinesRouteImport.update({
  id: '/legal/brand-guidelines',
  path: '/legal/brand-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiePolicyRoute = LegalCookiePolicyRouteImport.update({
  id: '/legal/cookie-policy',
  path: '/legal/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceEnterpriseRoute =
  LegalTermsOfServiceEnterpriseRouteImport.update({
    id: '/legal/terms-of-service-enterprise',
    path: '/legal/terms-of-service-enterprise',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiV1Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/agents.md': typeof AgentsDotmdRoute
  '/api': typeof ApiRouteWithChildren
  '/build-with-us': typeof BuildWithUsRoute
  '/company': typeof CompanyRoute
  '/compliance': typeof ComplianceRoute
  '/console': typeof ConsoleRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/dialogus': typeof DialogusRoute
  '/docs': typeof DocsRoute
  '/doutor-fiscal': typeof DoutorFiscalRoute
  '/download': typeof DownloadRoute
  '/enterprise': typeof EnterpriseRoute
  '/fcr': typeof FcrRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/infrastructure': typeof InfrastructureRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/queravaga': typeof QueravagaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sao-paulo': typeof SaoPauloRoute
  '/security': typeof SecurityRoute
  '/sitecreator': typeof SitecreatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/api/openapi.yaml': typeof ApiOpenapiDotyamlRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/api/versioning': typeof ApiVersioningRoute
  '/careers/open-roles': typeof CareersOpenRolesRoute
  '/legal/acceptable-use-policy': typeof LegalAcceptableUsePolicyRoute
  '/legal/brand-guidelines': typeof LegalBrandGuidelinesRoute
  '/legal/cookie-policy': typeof LegalCookiePolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/legal/terms-of-service-enterprise': typeof LegalTermsOfServiceEnterpriseRoute
  '/news/$slug': typeof NewsSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/careers/': typeof CareersIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/news/': typeof NewsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/agents.md': typeof AgentsDotmdRoute
  '/api': typeof ApiRouteWithChildren
  '/build-with-us': typeof BuildWithUsRoute
  '/company': typeof CompanyRoute
  '/compliance': typeof ComplianceRoute
  '/console': typeof ConsoleRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/dialogus': typeof DialogusRoute
  '/docs': typeof DocsRoute
  '/doutor-fiscal': typeof DoutorFiscalRoute
  '/download': typeof DownloadRoute
  '/enterprise': typeof EnterpriseRoute
  '/fcr': typeof FcrRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/infrastructure': typeof InfrastructureRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/queravaga': typeof QueravagaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sao-paulo': typeof SaoPauloRoute
  '/security': typeof SecurityRoute
  '/sitecreator': typeof SitecreatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/api/openapi.yaml': typeof ApiOpenapiDotyamlRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/api/versioning': typeof ApiVersioningRoute
  '/careers/open-roles': typeof CareersOpenRolesRoute
  '/legal/acceptable-use-policy': typeof LegalAcceptableUsePolicyRoute
  '/legal/brand-guidelines': typeof LegalBrandGuidelinesRoute
  '/legal/cookie-policy': typeof LegalCookiePolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/legal/terms-of-service-enterprise': typeof LegalTermsOfServiceEnterpriseRoute
  '/news/$slug': typeof NewsSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/careers': typeof CareersIndexRoute
  '/legal': typeof LegalIndexRoute
  '/news': typeof NewsIndexRoute
  '/solutions': typeof SolutionsIndexRoute
  '/work': typeof WorkIndexRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/agents.md': typeof AgentsDotmdRoute
  '/api': typeof ApiRouteWithChildren
  '/build-with-us': typeof BuildWithUsRoute
  '/company': typeof CompanyRoute
  '/compliance': typeof ComplianceRoute
  '/console': typeof ConsoleRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/dialogus': typeof DialogusRoute
  '/docs': typeof DocsRoute
  '/doutor-fiscal': typeof DoutorFiscalRoute
  '/download': typeof DownloadRoute
  '/enterprise': typeof EnterpriseRoute
  '/fcr': typeof FcrRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/infrastructure': typeof InfrastructureRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/queravaga': typeof QueravagaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sao-paulo': typeof SaoPauloRoute
  '/security': typeof SecurityRoute
  '/sitecreator': typeof SitecreatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/api/openapi.yaml': typeof ApiOpenapiDotyamlRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/api/versioning': typeof ApiVersioningRoute
  '/careers/open-roles': typeof CareersOpenRolesRoute
  '/legal/acceptable-use-policy': typeof LegalAcceptableUsePolicyRoute
  '/legal/brand-guidelines': typeof LegalBrandGuidelinesRoute
  '/legal/cookie-policy': typeof LegalCookiePolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/legal/terms-of-service-enterprise': typeof LegalTermsOfServiceEnterpriseRoute
  '/news/$slug': typeof NewsSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/careers/': typeof CareersIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/news/': typeof NewsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/agents.md'
    | '/api'
    | '/build-with-us'
    | '/company'
    | '/compliance'
    | '/console'
    | '/contact'
    | '/developers'
    | '/dialogus'
    | '/docs'
    | '/doutor-fiscal'
    | '/download'
    | '/enterprise'
    | '/fcr'
    | '/how-we-work'
    | '/infrastructure'
    | '/llms.txt'
    | '/openapi.json'
    | '/pricing'
    | '/products'
    | '/queravaga'
    | '/robots.txt'
    | '/sao-paulo'
    | '/security'
    | '/sitecreator'
    | '/sitemap.xml'
    | '/status'
    | '/api/openapi.yaml'
    | '/api/v1'
    | '/api/versioning'
    | '/careers/open-roles'
    | '/legal/acceptable-use-policy'
    | '/legal/brand-guidelines'
    | '/legal/cookie-policy'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/legal/terms-of-service-enterprise'
    | '/news/$slug'
    | '/solutions/$slug'
    | '/work/$slug'
    | '/careers/'
    | '/legal/'
    | '/news/'
    | '/solutions/'
    | '/work/'
    | '/api/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/agents.md'
    | '/api'
    | '/build-with-us'
    | '/company'
    | '/compliance'
    | '/console'
    | '/contact'
    | '/developers'
    | '/dialogus'
    | '/docs'
    | '/doutor-fiscal'
    | '/download'
    | '/enterprise'
    | '/fcr'
    | '/how-we-work'
    | '/infrastructure'
    | '/llms.txt'
    | '/openapi.json'
    | '/pricing'
    | '/products'
    | '/queravaga'
    | '/robots.txt'
    | '/sao-paulo'
    | '/security'
    | '/sitecreator'
    | '/sitemap.xml'
    | '/status'
    | '/api/openapi.yaml'
    | '/api/v1'
    | '/api/versioning'
    | '/careers/open-roles'
    | '/legal/acceptable-use-policy'
    | '/legal/brand-guidelines'
    | '/legal/cookie-policy'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/legal/terms-of-service-enterprise'
    | '/news/$slug'
    | '/solutions/$slug'
    | '/work/$slug'
    | '/careers'
    | '/legal'
    | '/news'
    | '/solutions'
    | '/work'
    | '/api/v1/$'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/agents.md'
    | '/api'
    | '/build-with-us'
    | '/company'
    | '/compliance'
    | '/console'
    | '/contact'
    | '/developers'
    | '/dialogus'
    | '/docs'
    | '/doutor-fiscal'
    | '/download'
    | '/enterprise'
    | '/fcr'
    | '/how-we-work'
    | '/infrastructure'
    | '/llms.txt'
    | '/openapi.json'
    | '/pricing'
    | '/products'
    | '/queravaga'
    | '/robots.txt'
    | '/sao-paulo'
    | '/security'
    | '/sitecreator'
    | '/sitemap.xml'
    | '/status'
    | '/api/openapi.yaml'
    | '/api/v1'
    | '/api/versioning'
    | '/careers/open-roles'
    | '/legal/acceptable-use-policy'
    | '/legal/brand-guidelines'
    | '/legal/cookie-policy'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/legal/terms-of-service-enterprise'
    | '/news/$slug'
    | '/solutions/$slug'
    | '/work/$slug'
    | '/careers/'
    | '/legal/'
    | '/news/'
    | '/solutions/'
    | '/work/'
    | '/api/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AgentsDotmdRoute: typeof AgentsDotmdRoute
  ApiRoute: typeof ApiRouteWithChildren
  BuildWithUsRoute: typeof BuildWithUsRoute
  CompanyRoute: typeof CompanyRoute
  ComplianceRoute: typeof ComplianceRoute
  ConsoleRoute: typeof ConsoleRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  DialogusRoute: typeof DialogusRoute
  DocsRoute: typeof DocsRoute
  DoutorFiscalRoute: typeof DoutorFiscalRoute
  DownloadRoute: typeof DownloadRoute
  EnterpriseRoute: typeof EnterpriseRoute
  FcrRoute: typeof FcrRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  InfrastructureRoute: typeof InfrastructureRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
  QueravagaRoute: typeof QueravagaRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SaoPauloRoute: typeof SaoPauloRoute
  SecurityRoute: typeof SecurityRoute
  SitecreatorRoute: typeof SitecreatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  CareersOpenRolesRoute: typeof CareersOpenRolesRoute
  LegalAcceptableUsePolicyRoute: typeof LegalAcceptableUsePolicyRoute
  LegalBrandGuidelinesRoute: typeof LegalBrandGuidelinesRoute
  LegalCookiePolicyRoute: typeof LegalCookiePolicyRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  LegalTermsOfServiceEnterpriseRoute: typeof LegalTermsOfServiceEnterpriseRoute
  NewsSlugRoute: typeof NewsSlugRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  CareersIndexRoute: typeof CareersIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents.md': {
      id: '/agents.md'
      path: '/agents.md'
      fullPath: '/agents.md'
      preLoaderRoute: typeof AgentsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-with-us': {
      id: '/build-with-us'
      path: '/build-with-us'
      fullPath: '/build-with-us'
      preLoaderRoute: typeof BuildWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialogus': {
      id: '/dialogus'
      path: '/dialogus'
      fullPath: '/dialogus'
      preLoaderRoute: typeof DialogusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doutor-fiscal': {
      id: '/doutor-fiscal'
      path: '/doutor-fiscal'
      fullPath: '/doutor-fiscal'
      preLoaderRoute: typeof DoutorFiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fcr': {
      id: '/fcr'
      path: '/fcr'
      fullPath: '/fcr'
      preLoaderRoute: typeof FcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queravaga': {
      id: '/queravaga'
      path: '/queravaga'
      fullPath: '/queravaga'
      preLoaderRoute: typeof QueravagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sao-paulo': {
      id: '/sao-paulo'
      path: '/sao-paulo'
      fullPath: '/sao-paulo'
      preLoaderRoute: typeof SaoPauloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitecreator': {
      id: '/sitecreator'
      path: '/sitecreator'
      fullPath: '/sitecreator'
      preLoaderRoute: typeof SitecreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.yaml': {
      id: '/api/openapi.yaml'
      path: '/openapi.yaml'
      fullPath: '/api/openapi.yaml'
      preLoaderRoute: typeof ApiOpenapiDotyamlRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/v1': {
      id: '/api/v1'
      path: '/v1'
      fullPath: '/api/v1'
      preLoaderRoute: typeof ApiV1RouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/versioning': {
      id: '/api/versioning'
      path: '/versioning'
      fullPath: '/api/versioning'
      preLoaderRoute: typeof ApiVersioningRouteImport
      parentRoute: typeof ApiRoute
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/open-roles': {
      id: '/careers/open-roles'
      path: '/careers/open-roles'
      fullPath: '/careers/open-roles'
      preLoaderRoute: typeof CareersOpenRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/acceptable-use-policy': {
      id: '/legal/acceptable-use-policy'
      path: '/legal/acceptable-use-policy'
      fullPath: '/legal/acceptable-use-policy'
      preLoaderRoute: typeof LegalAcceptableUsePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/brand-guidelines': {
      id: '/legal/brand-guidelines'
      path: '/legal/brand-guidelines'
      fullPath: '/legal/brand-guidelines'
      preLoaderRoute: typeof LegalBrandGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookie-policy': {
      id: '/legal/cookie-policy'
      path: '/legal/cookie-policy'
      fullPath: '/legal/cookie-policy'
      preLoaderRoute: typeof LegalCookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service-enterprise': {
      id: '/legal/terms-of-service-enterprise'
      path: '/legal/terms-of-service-enterprise'
      fullPath: '/legal/terms-of-service-enterprise'
      preLoaderRoute: typeof LegalTermsOfServiceEnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof ApiV1Route
    }
  }
}

interface ApiV1RouteChildren {
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

const ApiV1RouteChildren: ApiV1RouteChildren = {
  ApiV1SplatRoute: ApiV1SplatRoute,
}

const ApiV1RouteWithChildren = ApiV1Route._addFileChildren(ApiV1RouteChildren)

interface ApiRouteChildren {
  ApiOpenapiDotyamlRoute: typeof ApiOpenapiDotyamlRoute
  ApiV1Route: typeof ApiV1RouteWithChildren
  ApiVersioningRoute: typeof ApiVersioningRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiOpenapiDotyamlRoute: ApiOpenapiDotyamlRoute,
  ApiV1Route: ApiV1RouteWithChildren,
  ApiVersioningRoute: ApiVersioningRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AgentsDotmdRoute: AgentsDotmdRoute,
  ApiRoute: ApiRouteWithChildren,
  BuildWithUsRoute: BuildWithUsRoute,
  CompanyRoute: CompanyRoute,
  ComplianceRoute: ComplianceRoute,
  ConsoleRoute: ConsoleRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  DialogusRoute: DialogusRoute,
  DocsRoute: DocsRoute,
  DoutorFiscalRoute: DoutorFiscalRoute,
  DownloadRoute: DownloadRoute,
  EnterpriseRoute: EnterpriseRoute,
  FcrRoute: FcrRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  InfrastructureRoute: InfrastructureRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
  QueravagaRoute: QueravagaRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SaoPauloRoute: SaoPauloRoute,
  SecurityRoute: SecurityRoute,
  SitecreatorRoute: SitecreatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  CareersOpenRolesRoute: CareersOpenRolesRoute,
  LegalAcceptableUsePolicyRoute: LegalAcceptableUsePolicyRoute,
  LegalBrandGuidelinesRoute: LegalBrandGuidelinesRoute,
  LegalCookiePolicyRoute: LegalCookiePolicyRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  LegalTermsOfServiceEnterpriseRoute: LegalTermsOfServiceEnterpriseRoute,
  NewsSlugRoute: NewsSlugRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  CareersIndexRoute: CareersIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
